//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMode
    {
        public tblMode()
        {
            this.tblJeu = new HashSet<tblJeu>();
        }
    
        public int IdMode { get; set; }
        public string NomMode { get; set; }
        public string DescMode { get; set; }
    
        public virtual ICollection<tblJeu> tblJeu { get; set; }
    }
}
