USE dbProjetE2Test
GO
INSERT INTO Jeux.tblJeu(NomJeu,DescJeu,Actif,CoteESRB,IdGenre,IdMode)VALUES('Darkest dungeon','Darkest Dungeon est un jeu dont l"intérêt repose sur le stress provoqué par l"inconnu. Le joueur devra y monter une équipe de héros et les mener dans des lieux toujours plus effrayants pour leur faire combattre des monstres, mais aussi leurs peurs',1,'RP',25,1);
INSERT INTO Jeux.tblJeu(NomJeu,DescJeu,Actif,CoteESRB,IdGenre,IdMode)VALUES('FTL','Faster than Light. Le joueur a pour objectif de conduire son vaisseau d"un point A à un point B de la galaxie, en faisant face aux situations critiques qui se présentent à lui (attaques de pirates, dangers environnements), sur un mode aléatoire.',1,null,null,null);
INSERT INTO Jeux.tblJeu(NomJeu,DescJeu,Actif,CoteESRB,IdGenre,IdMode)VALUES('Halo 4 solo','Halo 4 est un jeu de tir en vue subjective sur Xbox 360. Septième jeu de la franchise Halo',1,'M',6,1);
INSERT INTO Jeux.tblJeu(NomJeu,DescJeu,Actif,CoteESRB,IdGenre,IdMode)VALUES('Halo 4 Multi local','Halo 4 est un jeu de tir en vue subjective sur Xbox 360. Septième jeu de la franchise Halo',1,'M',6,2);
INSERT INTO Jeux.tblJeu(NomJeu,DescJeu,Actif,CoteESRB,IdGenre,IdMode)VALUES('Halo 4 Multi en ligne','Halo 4 est un jeu de tir en vue subjective sur Xbox 360. Septième jeu de la franchise Halo',1,'M',6,3);
INSERT INTO Jeux.tblJeu(NomJeu,DescJeu,Actif,CoteESRB,IdGenre,IdMode)VALUES('Mario Kart 8 solo','Mario Kart 8 est un jeu de course. Mario et ses amis s"y affrontent a bord de karts ou de motos sur 32 circuits comprenant aussi bien des passages sous l"eau ou dans les airs que des loopings. Douze joueurs peuvent s"affronter en ligne ou 4 en local.',1,'E',1,1);
INSERT INTO Jeux.tblJeu(NomJeu,DescJeu,Actif,CoteESRB,IdGenre,IdMode)VALUES('Mario Kart 8 multi local','Mario Kart 8 est un jeu de course. Mario et ses amis s"y affrontent a bord de karts ou de motos sur 32 circuits comprenant aussi bien des passages sous l"eau ou dans les airs que des loopings. Douze joueurs peuvent s"affronter en ligne ou 4 en local.',1,'E',1,2);
INSERT INTO Jeux.tblJeu(NomJeu,DescJeu,Actif,CoteESRB,IdGenre,IdMode)VALUES('Mario Kart 8 multi en ligne','Mario Kart 8 est un jeu de course. Mario et ses amis s"y affrontent a bord de karts ou de motos sur 32 circuits comprenant aussi bien des passages sous l"eau ou dans les airs que des loopings. Douze joueurs peuvent s"affronter en ligne ou 4 en local.',1,'E',1,3);
INSERT INTO Jeux.tblJeu(NomJeu,DescJeu,Actif,CoteESRB,IdGenre,IdMode)VALUES('World of warcraft','World of Warcraft vous transporte dans le monde heroic-fantasy d"Azeroth où la guerre fait rage entre la Horde et l"Alliance. Affronter des hordes de monstres seul ou en groupe, constituer des guildes, et tellement plus encore.',1,'T',19,4);
INSERT INTO Jeux.tblJeu(NomJeu,DescJeu,Actif,CoteESRB,IdGenre,IdMode)VALUES('World of warcraft : Cataclysm','La 3ème extension de World of Warcraft, Cataclysm. le grand retour du tout puissant Deathwing qui va entraîner dans son sillage un changement radical de la topographie des continents. Arriver jusqu"au niveau 85 avec 2 nouvelles races',1,'T',19,4);
INSERT INTO Jeux.tblJeu(NomJeu,DescJeu,Actif,CoteESRB,IdGenre,IdMode)VALUES('NHL 15 solo','NHL 15 est une simulation de hockey sur glace. Ce nouvel épisode propose diverses améliorations physiques et graphiques, une foule d"aspect plus vivant, un nouveau commentateur ainsi que de nouvelles arènes exclusives.',1,'E10',40,1);
INSERT INTO Jeux.tblJeu(NomJeu,DescJeu,Actif,CoteESRB,IdGenre,IdMode)VALUES('NHL 15 Multi local','NHL 15 est une simulation de hockey sur glace. Ce nouvel épisode propose diverses améliorations physiques et graphiques, une foule d"aspect plus vivant, un nouveau commentateur ainsi que de nouvelles arènes exclusives.',1,'E10',40,2);
INSERT INTO Jeux.tblJeu(NomJeu,DescJeu,Actif,CoteESRB,IdGenre,IdMode)VALUES('NHL 15 multi en ligne','NHL 15 est une simulation de hockey sur glace. Ce nouvel épisode propose diverses améliorations physiques et graphiques, une foule d"spect plus vivant, un nouveau commentateur ainsi que de nouvelles arènes exclusives.',1,'E10',40,3);
INSERT INTO Jeux.tblJeu(NomJeu,DescJeu,Actif,CoteESRB,IdGenre,IdMode)VALUES('NHL 14 solo','NHL 14 est un jeu de hockey sur glace. Le joueur peut s"y prendre pour un professionnel et gérer sa propre carrière ou bien gérer l"avenir d"une franchise dans le mode DG. Des matchs old-school inspirés par NHL 94 sont également au programme.',1,'E10',40,1);
INSERT INTO Jeux.tblJeu(NomJeu,DescJeu,Actif,CoteESRB,IdGenre,IdMode)VALUES('NHL 14 Multi local','NHL 14 est un jeu de hockey sur glace. Le joueur peut s"y prendre pour un professionnel et gérer sa propre carrière ou bien gérer l"avenir d"une franchise dans le mode DG. Des matchs old-school inspirés par NHL 94 sont également au programme.',1,'E10',40,2);
INSERT INTO Jeux.tblJeu(NomJeu,DescJeu,Actif,CoteESRB,IdGenre,IdMode)VALUES('NHL 14 multi en ligne','NHL 14 est un jeu de hockey sur glace. Le joueur peut s"y prendre pour un professionnel et gérer sa propre carrière ou bien gérer l"avenir d"une franchise dans le mode DG. Des matchs old-school inspirés par NHL 94 sont également au programme.',1,'E10',40,3);
GO
USE master;