USE dbProjetE2Prod;
GO
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('DBABoFag','sauce','o','n','20151005',9,1,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('BoFag1','Chaussure','o','n','20151005',7,1,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('ChefEBoFag1','Rire','o','n','20151005',4,1,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('RoGau1','chaton','o','n','20151005',7,2,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('JeDuf1','password','o','n','20151005',7,3,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('MaTre1','Tremblay','o','n','20151005',7,4,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('EtMor1','Carlos','o','o','20151005',7,5,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('AlPar1','Parcour','o','n','20151005',7,6,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('ChefEAlPar1','Agile','o','n','20151005',4,18,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('MARou1','Roux','o','n','20151005',7,7,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('DirMARou1','DDC','o','b','20151005',2,7,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('DBAWiDub1','Will','o','n','20151005',9,8,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('YaGir1','Yann','o','n','20151005',7,9,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('ErPer1','temps','o','n','20151005',7,10,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('OlDup1','olivier','o','n','20151005',7,11,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('ChefPOlDup1','olivier','o','n','20151005',3,11,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('GaMor1','mort','o','n','20151005',7,12,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('DBARoGue1','admin','o','n','20151005',9,13,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('FePel1','pelle','o','n','20151005',7,14,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('JoLan1','defaut','o','n','20151005',7,15,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('JuFle1','fleur','o','n','20151005',7,16,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('ModJuFle1','fleur','o','n','20151005',6,16,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('ViRen1','rive','n','n','20151005',7,17,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('BeLeb1','belle','o','n','20151005',7,18,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('ChefEBeLeb1','Rouge','o','n','20151005',4,18,"o");
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp,Actif) values('ChefEJuPed1','Blanc','o','n','20151005',4,20,"o");
GO
use master;
