USE dbProjetE2Prod;
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('admin','admin',1,0,'20151005',1,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('RoGau1','chaton',1,0,'20151005',1,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('DBABoFag','sauce',1,0,'20151005',1,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('BoFag1','fagget',1,0,'20151005',1,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('JeDuf1','password',1,0,'20151005',1,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('MaTre1','okay',1,0,'20151005',1,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('EtMor1','Carlos',1,0,'20151005',1,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('AlPar1','Parcour',1,0,'20151005',1,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('MARou1','Roux',1,0,'20151005',1,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('WiDub1','Will',1,0,'20151005',1,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('YaGir1','Yann',1,0,'20151005',1,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('ErPer1','temps',1,0,'20151005',1,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('OlDup1','olivier',1,0,'20151005',1,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('GaMor1','mort',1,0,'20151005',1,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('RoGue1','admin',1,0,'20151005',1,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('FePel1','pelle',1,0,'20151005',1,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('JoLan1','defaut',1,0,'20151005',1,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('JuFle1','fleur',1,0,'20151005',1,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('ViRen1','riven',1,0,'20151005',1,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('BeLeb1','belle',1,0,'20151005',1,1);

