USE dbProjetE2Prod;
GO
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (1,100);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (8,100);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (9,100);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (15,100);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (4,101);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (7,101);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (16,102);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (1,103);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (2,103);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (4,103);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (5,103);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (6,103);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (7,103);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (11,103);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (12,103);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (19,103);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (20,103);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (2,104);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (16,104);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (6,105);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (10,105);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (19,105);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (11,106);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (12,106);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (17,106);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (1,107);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (2,107);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (4,107);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (19,107);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (1,108);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (8,108);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (13,108);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (3,109);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (7,109);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (6,110);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (16,110);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (19,110);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (3,111);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (5,111);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (8,112);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (13,112);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (18,112);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (20,112);
GO
use master;