USE dbProjetE2Prod;
GO
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('DBABoFag','sauce','o','n','20151005',9,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('BoFag1','Chaussure','o','n','20151005',7,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('ChefEBoFag1','Rire','o','n','20151005',4,1);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('RoGau1','chaton','o','n','20151005',7,2);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('JeDuf1','password','o','n','20151005',7,3);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('MaTre1','Tremblay','o','n','20151005',7,4);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('EtMor1','Carlos','o','o','20151005',7,5);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('AlPar1','Parcour','o','n','20151005',7,6);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('ChefEAlPar1','Agile','o','n','20151005',4,18);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('MARou1','Roux','o','n','20151005',7,7);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('DirMARou1','DDC','o','b','20151005',2,7);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('DBAWiDub1','Will','o','n','20151005',9,8);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('YaGir1','Yann','o','n','20151005',7,9);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('ErPer1','temps','o','n','20151005',7,10);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('OlDup1','olivier','o','n','20151005',7,11);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('ChefPOlDup1','olivier','o','n','20151005',3,11);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('GaMor1','mort','o','n','20151005',7,12);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('DBARoGue1','admin','o','n','20151005',9,13);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('FePel1','pelle','o','n','20151005',7,14);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('JoLan1','defaut','o','n','20151005',7,15);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('JuFle1','fleur','o','n','20151005',7,16);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('ModJuFle1','fleur','o','n','20151005',6,16);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('ViRen1','rive','n','n','20151005',7,17);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('BeLeb1','belle','o','n','20151005',7,18);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('ChefEBeLeb1','Rouge','o','n','20151005',4,18);
INSERT INTO Personnel.tblUtilisateur(NomUtil,MotPasUtil,PremiereConex,MotPasExpire,DateModifMotPas,IdRole,IdEmp) values('ChefEJuPed1','Blanc','o','n','20151005',4,20);
GO
use master;
