USE dbProjetE2Prod;
GO
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (1,1);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (8,1);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (9,1);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (15,1);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (4,2);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (7,2);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (16,3);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (1,4);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (2,4);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (4,4);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (5,4);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (6,4);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (7,4);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (11,4);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (12,4);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (19,4);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (20,4);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (2,5);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (16,5);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (6,6);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (10,6);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (19,6);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (11,7);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (12,7);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (17,7);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (1,8);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (2,8);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (4,8);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (19,8);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (1,9);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (8,9);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (13,9);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (3,10);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (7,10);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (6,11);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (16,11);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (19,11);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (3,12);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (5,12);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (8,13);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (13,13);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (18,13);
INSERT INTO Personnel.tblEquipeTesteur(IdEmp,IdEquipe) values (20,13);
GO
use master;