//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEquipe
    {
        public tblEquipe()
        {
            this.tblEmploye1 = new HashSet<tblEmploye>();
            this.tblTypeTest = new HashSet<tblTypeTest>();
        }
    
        public int IdEquipe { get; set; }
        public string NomEquipe { get; set; }
        public string CommentaireEquipe { get; set; }
        public string Statut { get; set; }
        public int IdChefEquipe { get; set; }
        public string CodeProjet { get; set; }
    
        public virtual tblEmploye tblEmploye { get; set; }
        public virtual ICollection<tblEmploye> tblEmploye1 { get; set; }
        public virtual ICollection<tblTypeTest> tblTypeTest { get; set; }
        public virtual tblProjet tblProjet { get; set; }
    }
}
