//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmParent
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_LEGO_ELODIEEntities : DbContext
    {
        public BD_LEGO_ELODIEEntities()
            : base("name=BD_LEGO_ELODIEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<colors> colors { get; set; }
        public virtual DbSet<messages> messages { get; set; }
        public virtual DbSet<pieces> pieces { get; set; }
        public virtual DbSet<pieces_users> pieces_users { get; set; }
        public virtual DbSet<sets> sets { get; set; }
        public virtual DbSet<sets_pieces> sets_pieces { get; set; }
        public virtual DbSet<sets_users> sets_users { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
