//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TexcelTest2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlateforme
    {
        public tblPlateforme()
        {
            this.tblJeu = new HashSet<tblJeu>();
            this.tblSysExp = new HashSet<tblSysExp>();
        }
    
        public int IdPlateforme { get; set; }
        public string CodePlateforme { get; set; }
        public string NomPlateforme { get; set; }
        public string CPU { get; set; }
        public string CarteMere { get; set; }
        public string RAM { get; set; }
        public string Stockage { get; set; }
        public string DescPlateforme { get; set; }
        public string InfoSupPlateforme { get; set; }
        public string Tag { get; set; }
        public string CodeCategorie { get; set; }
    
        public virtual tblCategorie tblCategorie { get; set; }
        public virtual ICollection<tblJeu> tblJeu { get; set; }
        public virtual ICollection<tblSysExp> tblSysExp { get; set; }
    }
}
