//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbProjetE2TestEntities : DbContext
    {
        public dbProjetE2TestEntities()
            : base("name=dbProjetE2TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCategorie> tblCategorie { get; set; }
        public virtual DbSet<tblClassification> tblClassification { get; set; }
        public virtual DbSet<tblGenre> tblGenre { get; set; }
        public virtual DbSet<tblJeu> tblJeu { get; set; }
        public virtual DbSet<tblMode> tblMode { get; set; }
        public virtual DbSet<tblPlateforme> tblPlateforme { get; set; }
        public virtual DbSet<tblSysExp> tblSysExp { get; set; }
        public virtual DbSet<tblTheme> tblTheme { get; set; }
        public virtual DbSet<tblVersion> tblVersion { get; set; }
        public virtual DbSet<tblDroit> tblDroit { get; set; }
        public virtual DbSet<tblEmploye> tblEmploye { get; set; }
        public virtual DbSet<tblEquipe> tblEquipe { get; set; }
        public virtual DbSet<tblGroupe> tblGroupe { get; set; }
        public virtual DbSet<tblRole> tblRole { get; set; }
        public virtual DbSet<tblUtilisateur> tblUtilisateur { get; set; }
        public virtual DbSet<tblFiltre1> tblFiltre1 { get; set; }
        public virtual DbSet<tblFiltre2> tblFiltre2 { get; set; }
        public virtual DbSet<tblFiltre3> tblFiltre3 { get; set; }
        public virtual DbSet<tblCasTest> tblCasTest { get; set; }
        public virtual DbSet<tblProjet> tblProjet { get; set; }
        public virtual DbSet<tblTypeTest> tblTypeTest { get; set; }
        public virtual DbSet<AllChefEquipe> AllChefEquipe { get; set; }
        public virtual DbSet<AllEmployeRole> AllEmployeRole { get; set; }
        public virtual DbSet<VProjetRecherche> VProjetRecherche { get; set; }
        public virtual DbSet<VTypeTestRecherche> VTypeTestRecherche { get; set; }
        public virtual DbSet<VVersionRecherche> VVersionRecherche { get; set; }
        public virtual DbSet<AllChefProjet> AllChefProjet { get; set; }
        public virtual DbSet<AllTesteur> AllTesteur { get; set; }
        public virtual DbSet<VCasTest> VCasTest { get; set; }
        public virtual DbSet<VCategorie> VCategorie { get; set; }
        public virtual DbSet<VClassification> VClassification { get; set; }
        public virtual DbSet<VDroit> VDroit { get; set; }
        public virtual DbSet<VEmploye> VEmploye { get; set; }
        public virtual DbSet<VEmployeTypeTest> VEmployeTypeTest { get; set; }
        public virtual DbSet<VEquipe> VEquipe { get; set; }
        public virtual DbSet<VEquipeTypeTest> VEquipeTypeTest { get; set; }
        public virtual DbSet<VGenre> VGenre { get; set; }
        public virtual DbSet<VGroupe> VGroupe { get; set; }
        public virtual DbSet<VGroupeDroit> VGroupeDroit { get; set; }
        public virtual DbSet<VGroupeUtil> VGroupeUtil { get; set; }
        public virtual DbSet<VJeu> VJeu { get; set; }
        public virtual DbSet<VJeuSemblable> VJeuSemblable { get; set; }
        public virtual DbSet<VMode> VMode { get; set; }
        public virtual DbSet<VPlateforme> VPlateforme { get; set; }
        public virtual DbSet<VPlateformeJeu> VPlateformeJeu { get; set; }
        public virtual DbSet<VPlateformeSysExp> VPlateformeSysExp { get; set; }
        public virtual DbSet<VProjet> VProjet { get; set; }
        public virtual DbSet<VRole> VRole { get; set; }
        public virtual DbSet<VTheme> VTheme { get; set; }
        public virtual DbSet<VThemeJeu> VThemeJeu { get; set; }
        public virtual DbSet<VTypeTest> VTypeTest { get; set; }
        public virtual DbSet<VUtilisateur> VUtilisateur { get; set; }
        public virtual DbSet<VVersion> VVersion { get; set; }
    
        [DbFunction("dbProjetE2TestEntities", "GetEmployeByRole")]
        public virtual IQueryable<GetEmployeByRole_Result> GetEmployeByRole(Nullable<int> role)
        {
            var roleParameter = role.HasValue ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetEmployeByRole_Result>("[dbProjetE2TestEntities].[GetEmployeByRole](@role)", roleParameter);
        }
    }
}
