//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFiltre3
    {
        public int IdFiltre3 { get; set; }
        public string NomFiltre3 { get; set; }
        public string DescFiltre3 { get; set; }
        public string NomVue { get; set; }
        public int IdFiltre2 { get; set; }
    }
}
