//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VJeu
    {
        public int IdJeu { get; set; }
        public string NomJeu { get; set; }
        public string DescJeu { get; set; }
        public bool Actif { get; set; }
        public string InfoSupJeu { get; set; }
        public string Tag { get; set; }
        public string CoteESRB { get; set; }
        public Nullable<int> IdGenre { get; set; }
        public Nullable<int> IdMode { get; set; }
    }
}
