//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPlateforme
    {
        public int IdPlateforme { get; set; }
        public string CodePlateforme { get; set; }
        public string NomPlateforme { get; set; }
        public string CPU { get; set; }
        public string CarteMere { get; set; }
        public string RAM { get; set; }
        public string Stockage { get; set; }
        public string DescPlateforme { get; set; }
        public string InfoSupPlateforme { get; set; }
        public string Tag { get; set; }
        public string CodeCategorie { get; set; }
    }
}
