//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VProjet
    {
        public string CodeProjet { get; set; }
        public string TitreProjet { get; set; }
        public string ObjectifProjet { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public Nullable<System.DateTime> DateEcheance { get; set; }
        public string DescProjet { get; set; }
        public string Autre { get; set; }
        public string CodeVersion { get; set; }
        public Nullable<int> IdChefProjet { get; set; }
    }
}
