//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTypeTestRecherche
    {
        public string CodeTypeTest { get; set; }
        public string NomTypeTest { get; set; }
        public string ObjectifTypeTest { get; set; }
        public string DescTypeTest { get; set; }
        public string CommentaireTest { get; set; }
    }
}
