//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VUtilisateur
    {
        public string NomUtil { get; set; }
        public string MotPasUtil { get; set; }
        public string PremiereConex { get; set; }
        public string MotPasExpire { get; set; }
        public Nullable<System.DateTime> DateModifMotPas { get; set; }
        public int IdRole { get; set; }
        public int IdEmp { get; set; }
        public string Actif { get; set; }
    }
}
