//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VVersion
    {
        public string CodeVersion { get; set; }
        public string NomVersion { get; set; }
        public string DescVersion { get; set; }
        public string StadeDeveloppement { get; set; }
        public System.DateTime DateVersion { get; set; }
        public Nullable<System.DateTime> DateSortiePrevue { get; set; }
        public string Tag { get; set; }
        public int IdJeu { get; set; }
    }
}
