USE dbProjetE2Test;
GO
INSERT INTO Test.tblCasTest(CodeCas, CodeProjet, TitreCas,ObjectifCas,DateEcheance,DateCreation,DescCas,StatutCas,InfoSupCas,DiffculteCas,UrgenceCas, CodeTypeTest,Auteur) VALUES ('1TestHalo5','PHalo5Beta', 'Premier test d''une suite de trois test pour halo5','2015-03-12','2015-06-08','Cas de test de test','en pause','','Faible','Moyen','CoWal');
INSERT INTO Test.tblCasTest(CodeCas, CodeProjet, TitreCas,ObjectifCas,DateEcheance,DateCreation,DescCas,StatutCas,InfoSupCas,DiffculteCas,UrgenceCas, CodeTypeTest,Auteur) VALUES ('2TestHalo5','PHalo5Beta', 'Deuxieme test d''une suite de trois test pour halo5','2015-03-12','2015-06-01','Test des truc quand meme cool','en cours','','Elevee','Elevee','CoWal');
INSERT INTO Test.tblCasTest(CodeCas, CodeProjet, TitreCas,ObjectifCas,DateEcheance,DateCreation,DescCas,StatutCas,InfoSupCas,DiffculteCas,UrgenceCas, CodeTypeTest,Auteur) VALUES ('3TestHalo5','PHalo5Beta', 'Dernier test d''une suite de trois test pour halo5','2015-03-12','2015-05-17','Super test de la mort qui tue','Terminer','','Faible','Faible','CoWal');
INSERT INTO Test.tblCasTest(CodeCas, CodeProjet, TitreCas,ObjectifCas,DateEcheance,DateCreation,DescCas,StatutCas,InfoSupCas,DiffculteCas,UrgenceCas, CodeTypeTest,Auteur) VALUES ('1SoCaTest5','PSC5BetaMu', 'Un super test de la mort sur soul calibur 5','2014-02-06','2014-03-08','Cas de test de cas de test de test','en pause','','Faible','Moyen','CoWal');
INSERT INTO Test.tblCasTest(CodeCas, CodeProjet, TitreCas,ObjectifCas,DateEcheance,DateCreation,DescCas,StatutCas,InfoSupCas,DiffculteCas,UrgenceCas, CodeTypeTest,Auteur) VALUES ('2SoCaTest5','PSC5BetaMu', 'Un autre test sur soul calibur 5','2014-02-06','2014-04-03','Test de truc plus cool que dans l''autre test','en cours','','Elevee','Elevee','CoWal');

GO
USE master;