USE dbProjetE2Test;
GO
INSERT INTO Test.tblCasTest(CodeCas, CodeProjet, TitreCas,ObjectifCas,DateEcheance,DateCreation,DescCas,StatutCas,InfoSupCas,DifficulteCas,PrioriteCas, CodeTypeTest,IdAuteur) VALUES ('1TestHalo5','PHalo5Beta', 'Halo5.1','Premier test d''une suite de trois test pour halo5','2015-03-12','2015-06-08','Cas de test de test','en pause','','Faible','Moyen','CoWal',8);
INSERT INTO Test.tblCasTest(CodeCas, CodeProjet, TitreCas,ObjectifCas,DateEcheance,DateCreation,DescCas,StatutCas,InfoSupCas,DifficulteCas,PrioriteCas, CodeTypeTest,IdAuteur) VALUES ('2TestHalo5','PHalo5Beta', 'Halo5.2','Deuxieme test d''une suite de trois test pour halo5','2015-03-12','2015-06-01','Test des truc quand meme cool','en cours','','Elevee','Elevee','CoWal',1);
INSERT INTO Test.tblCasTest(CodeCas, CodeProjet, TitreCas,ObjectifCas,DateEcheance,DateCreation,DescCas,StatutCas,InfoSupCas,DifficulteCas,PrioriteCas, CodeTypeTest,IdAuteur) VALUES ('3TestHalo5','PHalo5Beta', 'Halo5.3','Dernier test d''une suite de trois test pour halo5','2015-03-12','2015-05-17','Super test de la mort qui tue','Terminer','','Faible','Faible','CoWal',4);
INSERT INTO Test.tblCasTest(CodeCas, CodeProjet, TitreCas,ObjectifCas,DateEcheance,DateCreation,DescCas,StatutCas,InfoSupCas,DifficulteCas,PrioriteCas, CodeTypeTest,IdAuteur) VALUES ('1SoCaTest5','PSC5BetaMu', 'SoulCal5.1','Un super test de la mort sur soul calibur 5','2014-02-06','2014-03-08','Cas de test de cas de test de test','en pause','','Faible','Moyen','CoWal',8);
INSERT INTO Test.tblCasTest(CodeCas, CodeProjet, TitreCas,ObjectifCas,DateEcheance,DateCreation,DescCas,StatutCas,InfoSupCas,DifficulteCas,PrioriteCas, CodeTypeTest,IdAuteur) VALUES ('2SoCaTest5','PSC5BetaMu', 'SoulCal5.2','Un autre test sur soul calibur 5','2014-02-06','2014-04-03','Test de truc plus cool que dans l''autre test','en cours','','Elevee','Elevee','CoWal',3);

GO
USE master;