//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbProjetE2TestEntities : DbContext
    {
        public dbProjetE2TestEntities()
            : base("name=dbProjetE2TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblCategorie> tblCategorie { get; set; }
        public virtual DbSet<tblClassification> tblClassification { get; set; }
        public virtual DbSet<tblGenre> tblGenre { get; set; }
        public virtual DbSet<tblJeu> tblJeu { get; set; }
        public virtual DbSet<tblMode> tblMode { get; set; }
        public virtual DbSet<tblPlateforme> tblPlateforme { get; set; }
        public virtual DbSet<tblSysExp> tblSysExp { get; set; }
        public virtual DbSet<tblTheme> tblTheme { get; set; }
        public virtual DbSet<tblVersion> tblVersion { get; set; }
        public virtual DbSet<tblDroit> tblDroit { get; set; }
        public virtual DbSet<tblEmploye> tblEmploye { get; set; }
        public virtual DbSet<tblEquipe> tblEquipe { get; set; }
        public virtual DbSet<tblGroupe> tblGroupe { get; set; }
        public virtual DbSet<tblRole> tblRole { get; set; }
        public virtual DbSet<tblUtilisateur> tblUtilisateur { get; set; }
        public virtual DbSet<tblCasTest> tblCasTest { get; set; }
        public virtual DbSet<tblProjet> tblProjet { get; set; }
        public virtual DbSet<tblTypeTest> tblTypeTest { get; set; }
    }
}
