//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFiltre2
    {
        public tblFiltre2()
        {
            this.tblFiltre3 = new HashSet<tblFiltre3>();
        }
    
        public int IdFiltre2 { get; set; }
        public string NomFiltre2 { get; set; }
        public string DescFiltre2 { get; set; }
        public string NomVue { get; set; }
        public int IdFiltre1 { get; set; }
    
        public virtual tblFiltre1 tblFiltre1 { get; set; }
        public virtual ICollection<tblFiltre3> tblFiltre3 { get; set; }
    }
}
