//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGroupe
    {
        public tblGroupe()
        {
            this.tblDroit = new HashSet<tblDroit>();
            this.tblUtilisateur = new HashSet<tblUtilisateur>();
        }
    
        public int IdGroupe { get; set; }
        public string NomGroupe { get; set; }
    
        public virtual ICollection<tblDroit> tblDroit { get; set; }
        public virtual ICollection<tblUtilisateur> tblUtilisateur { get; set; }
    }
}
