//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRole
    {
        public tblRole()
        {
            this.tblUtilisateur = new HashSet<tblUtilisateur>();
        }
    
        public int IdRole { get; set; }
        public string NomRole { get; set; }
        public string DescRole { get; set; }
    
        public virtual ICollection<tblUtilisateur> tblUtilisateur { get; set; }
    }
}
