//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTheme
    {
        public tblTheme()
        {
            this.tblJeu = new HashSet<tblJeu>();
        }
    
        public int IdTheme { get; set; }
        public string NomTheme { get; set; }
        public string ComTheme { get; set; }
    
        public virtual ICollection<tblJeu> tblJeu { get; set; }
    }
}
