//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSysExp
    {
        public tblSysExp()
        {
            this.tblPlateforme = new HashSet<tblPlateforme>();
        }
    
        public int IdSysExp { get; set; }
        public string CodeSysExp { get; set; }
        public string NomSysExp { get; set; }
        public string EditionSysExp { get; set; }
        public string VersionSysExp { get; set; }
        public string InfoSupSysExp { get; set; }
        public string Tag { get; set; }
    
        public virtual ICollection<tblPlateforme> tblPlateforme { get; set; }
    }
}
