USE dbProjetE2Prod;
INSERT INTO Jeux.tblGenre(NomGenre,ComGenre) VALUES('Course ','Les jeux de Vroum vroum');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Action Combat');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Action Beat them all');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Action Plates-formes');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Action Tir');
INSERT INTO Jeux.tblGenre(NomGenre,ComGenre) VALUES('Action Tir en vue subjective','Les FPS, First person shooter');
INSERT INTO Jeux.tblGenre(NomGenre,ComGenre) VALUES('Action Shoot them up','aussi appeller Shmup');
INSERT INTO Jeux.tblGenre(NomGenre,ComGenre) VALUES('Action Rail Shooter','Le joueur ne décide pas des mouvement fait par le personnage');
INSERT INTO Jeux.tblGenre(NomGenre,ComGenre) VALUES('Action Tir en vue objective','Les TPS, Third person shooter');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Aventure ');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Aventure Fiction interactive');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Aventure graphique');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Aventure Simulation de drague');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Aventure Visuel novel');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Action-Aventure ');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Action-Aventure Infiltration');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Action-Aventure Survival horror');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Gestion');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('RPG ');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('RPG Gestion');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('RPG d''action');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('RPG Hack''n''slash');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('RPG tour par tour');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('RPG Rogue-like');
INSERT INTO Jeux.tblGenre(NomGenre,ComGenre) VALUES('RPG Rogue-like tour par tour','Un jeu où vous mourez à chaque tour');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('RPG tactique');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Réflexion ');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Réflexion Labyrinthe');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Réflexion Puzzle');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Simulation ');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Simulation Gestion');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Simulation God Game');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Simulation de véhicule');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Stratégie ');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Stratégie au tour par tour');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Stratégie en temps réel');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Stratégie Grande stratégie');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Stratégie 4X');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Stratégie Wargame');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Sport ');
INSERT INTO Jeux.tblGenre(NomGenre,ComGenre) VALUES('Dessin ', 'Jeux créatifs');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('Rythme ');
INSERT INTO Jeux.tblGenre(NomGenre) VALUES('RPG FPS');
USE master;
