USE dbProjetE2Prod
GO
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(1,1);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(2,1);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(3,1);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(12,1);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(18,1);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(1,2);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(2,2);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(3,2);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(6,2);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(7,2);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(8,2);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(9,2);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(18,2);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(16,3);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(16,4);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(16,5);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(17,8);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(1,9);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(2,9);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(3,9);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(18,9);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(1,10);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(2,10);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(3,10);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(18,10);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(12,11);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(14,11);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(15,11);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(16,11);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(12,12);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(14,12);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(15,12);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(16,12);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(12,13);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(14,13);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(15,13);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(16,13);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(15,14);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(16,14);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(15,15);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(16,15);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(15,16);
INSERT INTO Jeux.tblPlateformeJeu(IdPlateforme,IdJeu) VALUES(16,16);
GO
USE master;