USE dbProjetE2Prod;
GO
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Abeilles');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Abstrait');
INSERT INTO Jeux.tblTheme(NomTheme,ComTheme) VALUES('Adaptation littéraire','Une adaptation d''un roman sous format vidéoludique');
INSERT INTO Jeux.tblTheme(NomTheme,ComTheme) VALUES('Affrontement guerrier','Un jeu qui tourne autour des combats, gladiateur, guerre, etc');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Afrique');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Allemagne');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Alpinisme');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Amérique');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Angleterre');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Animaux');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Animaux champêtres');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Animaux domestiques');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Animaux exotiques');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Animaux insectes');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Animaux marins');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Anniversaire');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Antiquité');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Araignées');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Archéologie');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Architecture');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Argentine');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Art');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Arts martiaux');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Asie');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Atlantide');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Australie');
INSERT INTO Jeux.tblTheme(NomTheme,ComTheme) VALUES('Automobile','Un jeu où pratiquement  tout tourne autour des voiture');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Autriche');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Avion');
INSERT INTO Jeux.tblTheme(NomTheme,ComTheme) VALUES('Avions','Je ne comprend pas ces quoi la diffèrence avec l''autre');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Ânes');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Baleines');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Banquise');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Bar');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Base spatiale');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Belgique');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Bergers');
INSERT INTO Jeux.tblTheme(NomTheme,ComTheme) VALUES('Billard','Pour les jeu qui ne comporte que du billard, pas comme un mini-jeux');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Boissons');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Brocante');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Cache-Cache');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Cadeaux');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Café');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Cambriolage');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Camions');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Camping');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Canards');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Caractère');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Caraïbes');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Casino');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Chameaux');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Charbon');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Chasse');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Chasse au trésor');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Chats');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Château');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Chevalerie');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Chevaux');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Chèvres');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Chiens');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Chine');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Chocolat');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Cinéma');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Cirque');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Clowns');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Coccinelles');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Cochons');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Colonisation');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Commerce');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Confrontation');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Conquête de l''Ouest');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Conte');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Contes');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Corps humain');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Corse');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Costumes / Déguisements');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Couleurs');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Course');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Cowboys');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Cowboys / Indiens');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Crabes');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Crevettes');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Crocodiles');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Cuisine');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Cuisine / Boisson');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Culture / Agriculture');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Culture générale');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Danse');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Dessin');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Défis');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Dérive des continents');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Désert');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Développement');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Diable');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Diamants');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Dinosaures');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Dragons');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Duel');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Eau');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Egypte');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Enfants');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Enquête');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Environnement Aquatique');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Environnement Banquise');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Environnement Château');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Environnement Décharge publique');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Environnement Désert');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Environnement étang');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Environnement Ferme');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Environnement Grotte');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Environnement Hotel / Restaurant / Café');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Environnement Île');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Environnement Jardin');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Environnement Jungle / Forêt');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Environnement Monastère');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Environnement Montagne');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Environnement Sous-Marin');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Environnement Ville');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Environnement Volcan');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Environnement Zoo');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Escalade');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Escrime');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Espace');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Espagne');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Espionnage');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Europe');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Exploration');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Extra-terrestres');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Écologie');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Écosse');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Écureuils');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Élevage');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Éléphants');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Énergie');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Époque victorienne');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Étang');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Évasion');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Famille');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Fantastique');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Fantômes');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Ferme');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Feu d''artifice');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Fête');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Filles / Garçons');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Fleurs');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Football');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Forêt');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Formes');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Formule 1');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Fouille');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Fourmis');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('France');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Fromage');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Fruits / Légumes');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Fusées');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Gendarmes / Voleurs');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Géographie');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Girafes');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Grenouilles');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Grêce');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Grotte');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Guerre Mondiale');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Heroic-fantaisy');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Histoire');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Histoire Antiquité');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Histoire biblique');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Histoire Guerre Mondiale');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Histoire Médiévale');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Histoire Renaissance');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Histoire Sixties');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Horreur');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Hotel / Restaurant / Café');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Improvisation');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Industrie');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Informatique');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Insectes');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Invention');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Italie');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Île');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Japon');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Jardin');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Jeux de cirque');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Jeux vidéo');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Joaillerie');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Jungle / Forêt');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Kermesse');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Killer');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Labyinthe');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Labyrinthe');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lapins');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Légende');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu Afrique');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu Allemagne');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu Amérique');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu Amérique du Sud');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu Angleterre');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu Asie');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu Australie');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu Autriche');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu Belgique');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu Caraïbes');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu Caraïbes Plage');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu Ecosse');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu Espagne');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu Europe');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu France');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu Grêce');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu Italie');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu Méditérranée');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu Monde');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu Pacifique');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu Proche-Orient');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lieu Suisse');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Linguistique');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Livre');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Loups');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Lune');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Mafia');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Magie / Sorcellerie');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Maison');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Marché / Bourse');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Mer');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Merveilles du monde');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Médecine');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Méditérranée');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Mille et une nuits');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Mine');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Monastère');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Monde');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Monstres');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Montagne');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Montgolfières');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Moto');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Mots / Lettres');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Mouches');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Moutons');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Moyen-age');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Musique');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Musique / Chansons');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Mythologie');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Napoléon');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Nature');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Naufrage');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Neige');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Nombres / Chiffres');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Oiseaux');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Ombres');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Ours');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Pacifique');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Pandas');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Papillons');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Peinture');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Pêche');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Photographie');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Pierres précieuses');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Pingouins');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Piraterie');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Pirates');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Piscine');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Pizzas');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Plage');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Poésie');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Poissons');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Poker');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Politique');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Pompiers');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Port');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Potion magique');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Poules');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Poulpes');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Pôle Nord');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Préhistoire');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Prison');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Proche-Orient');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Recette');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Recherche');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Renaissance');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Renards');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Repas');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Requins');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Rêves');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Rhinocéros');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Rivière');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Robots');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Ruée vers l''or');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Saisons');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Samourai');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Science-Fiction');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Senji');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Serpents');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Singes');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Sixties');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Soleil');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Souris');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Sous-marin');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Sport');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Sport Arts martiaux');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Sport Automobile');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Sport Cyclisme');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Sport Football');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Sport Hippique');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Sport Nautique');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Suisse');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Taupes');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Temps');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Théâtre');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Tortues');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Tourisme');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Tournoi');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Train');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Transport aérien');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Transport automobile');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Transport ferroviaire');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Transport marin');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Transport spatial');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Travail / Bureau');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Urbanisme / Construction');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Vacances');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Vaches');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Vaisseau spatial');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Vautours');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Vers');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Vélo');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Vêtements');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Vikings');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Ville');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Vin');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Vocabulaire');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Voitures');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Volcan');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Voyage');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Voyage dans le temps');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Voyance / Divination');
INSERT INTO Jeux.tblTheme(NomTheme,ComTheme) VALUES('Western','Les jeux avec des beaux chapeaux');
INSERT INTO Jeux.tblTheme(NomTheme) VALUES('Zombies');