USE dbProjetE2Test;
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('WinXPFam','Windows XP','Familiale','32bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('WinXPPro','Windows XP','Professionel','32bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('WinXPPro','Windows XP','Professionel','64bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Start','Windows 7','Starter','32bit Service Pack 1');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7HBas','Windows 7','Home Basic','32bit Service Pack 1');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7HPrem','Windows 7','Home Premium','32bit Service Pack 1');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Pro','Windows 7','Home Professional','32bit Service Pack 1');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Entr','Windows 7','Entreprise','32bit Service Pack 1');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Ult','Windows 7','Ultimate','32bit Service Pack 1');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Start','Windows 7','Starter','32bit Service Pack 2');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7HBas','Windows 7','Home Basic','32bit Service Pack 2');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7HPrem','Windows 7','Home Premium','32bit Service Pack 2');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Pro','Windows 7','Home Professional','32bit Service Pack 2');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Entr','Windows 7','Entreprise','32bit Service Pack 2');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Ult','Windows 7','Ultimate','32bit Service Pack 2');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Start','Windows 7','Starter','64bit Service Pack 1');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7HBas','Windows 7','Home Basic','64bit Service Pack 1');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7HPrem','Windows 7','Home Premium','64bit Service Pack 1');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Pro','Windows 7','Home Professional','64bit Service Pack 1');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Entr','Windows 7','Entreprise','64bit Service Pack 1');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Ult','Windows 7','Ultimate','64bit Service Pack 1');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Start','Windows 7','Starter','64bit Service Pack 2');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7HBas','Windows 7','Home Basic','64bit Service Pack 2');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7HPrem','Windows 7','Home Premium','64bit Service Pack 2');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Pro','Windows 7','Home Professional','64bit Service Pack 2');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Entr','Windows 7','Entreprise','64bit Service Pack 2');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Ult','Windows 7','Ultimate','64bit Service Pack 2');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Start','Windows 7','Starter','32bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7HBas','Windows 7','Home Basic','32bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7HPrem','Windows 7','Home Premium','32bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Pro','Windows 7','Home Professional','32bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Entr','Windows 7','Entreprise','32bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Ult','Windows 7','Ultimate','32bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Start','Windows 7','Starter','64bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7HBas','Windows 7','Home Basic','64bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7HPrem','Windows 7','Home Premium','64bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Pro','Windows 7','Home Professional','64bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Entr','Windows 7','Entreprise','64bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win7Ult','Windows 7','Ultimate','64bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win8','Windows 8','Basic','32bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win8Pro','Windows 8','Professionnel','32bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win8Entr','Windows 8','Entreprise','32bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win8RT','Windows 8','RT','32bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win8','Windows 8','Basic','64bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win8Pro','Windows 8','Professionnel','64bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win8Entr','Windows 8','Entreprise','64bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win8RT','Windows 8','RT','64bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win8.1','Windows 8','Basic','32bit Service Pack 1');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win8.1Pro','Windows 8','Professionnel','32bit Service Pack 1');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win8.1Entr','Windows 8','Entreprise','32bit Service Pack 1');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win8.1RT','Windows 8','RT','32bit Service Pack 1');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win8.1','Windows 8','Basic','64bit Service Pack 1');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win8.1Pro','Windows 8','Professionnel','64bit Service Pack 1');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win8.1Entr','Windows 8','Entreprise','64bit Service Pack 1');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win8.1RT','Windows 8','RT','64bit Service Pack 1');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win10home','Windows 10','Home','32bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win10Pro','Windows 10','Professionnel','32bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win10Entr','Windows 10','Entreprise','32bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win10LTSB','Windows 10','Entreprise LTSB','32bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win10Edu','Windows 10','Education','32bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win10Mob','Windows 10','Mobile','32bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win10MoEtr','Windows 10','Mobile Entreprise','32bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win10Core','Windows 10','Core','32bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win10home','Windows 10','Home','64bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win10Pro','Windows 10','Professionnel','64bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win10Entr','Windows 10','Entreprise','64bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win10LTSB','Windows 10','Entreprise LTSB','64bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win10Edu','Windows 10','Education','64bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win10Mob','Windows 10','Mobile','64bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win10MoEtr','Windows 10','Mobile Entreprise','64bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,VersionSysExp) VALUES('Win10Core','Windows 10','Core','64bit');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,InfoSupSysExp) VALUES('XBoxOS','XBox OS','Xbox One','Système d''exploitation XBox One');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,InfoSupSysExp) VALUES('Ps4OS','Orbis OS','Ps4','Système d''exploitation Ps4');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,InfoSupSysExp) VALUES('Ps3OS','Cell OS','Ps3',null);
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,InfoSupSysExp) VALUES('XBoxDash','Xbox 360 DashBoard','Xbox 360','Système d''exploitation XBox 360');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,InfoSupSysExp) VALUES('WiiUSys','Wii U System Software','Wii U','Système d''exploitation Wii U');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,InfoSupSysExp) VALUES('3DSSys','3DS System Software','3DS','Système d''exploitation 3DS');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,InfoSupSysExp) VALUES('iOS9','iOS','9','Système d''exploitation pour mobile Apple');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,InfoSupSysExp) VALUES('And5','Android','Lollipop 5.0','Système d''exploitation Android');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,InfoSupSysExp) VALUES('iOS8','iOS','8','Système d''exploitation pour mobile Apple');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,InfoSupSysExp) VALUES('PSVitaOS','PSVita OS','Version 3','Système d''exploitation PS Vita');
INSERT INTO Jeux.tblSysExp(CodeSysExp,NomSysExp,EditionSysExp,InfoSupSysExp) VALUES('OSX','OS','X','Système d''exploitation MAC');
USE master;