USE dbProjetE2Test;
GO
INSERT INTO Jeux.tblPlateforme(CodePlateforme,NomPlateforme,CPU,RAM,Stockage,DescPlateforme,InfoSupPlateforme,CodeCategorie) VALUES('Alien','Alienware15','4e génération Intel Core jusqu''à i7','DDR4 de 8 Go 2133MHz (4Gox2)','Disque dur SATA de 1 To à 7 200 tr/min et 6 Gbit/s','Portable Élite','NVIDIA® GeForce® GTX 965M with 2GB GDDR5','PCPort');
INSERT INTO Jeux.tblPlateforme(CodePlateforme,NomPlateforme,CPU,CarteMere,RAM,Stockage,DescPlateforme,InfoSupPlateforme,CodeCategorie) VALUES('OptiPlex','OptiPlex 3030 tout-en-un','Intel® Celeron® G1840','Intel Core','DDR3L 4 Go3 à 1600 MHz','Disque dur de 500Go, 7200 t/min','Ordinateur d''entreprise  ','Carte graphique Intel® intégrée','PCBur');
INSERT INTO Jeux.tblPlateforme(CodePlateforme,NomPlateforme,CPU,CarteMere,RAM,Stockage,DescPlateforme,InfoSupPlateforme,CodeCategorie) VALUES('Aspire','Ordinateur Aspire TC d''Acer','Core i5 4e génération d''Intel ','Aspire TC, Acer','8 Go de mémoire vive','Disque dur de 1 To','Ordinateur moins performante','carte graph. HD 4600 Intel','PCBur');
INSERT INTO Jeux.tblPlateforme(CodePlateforme,NomPlateforme,CPU,CarteMere,RAM,Stockage,DescPlateforme,InfoSupPlateforme,CodeCategorie) VALUES('Samsung','Samsung Galaxy S5','2,5 GHz Quadricoeur','Qualcomm MSM8974AC Snapdragon 801','16 Go','2 Go','Téléphone intelligent Android de petit format','Micro-SIM (3FF)','Mobile');
INSERT INTO Jeux.tblPlateforme(CodePlateforme,NomPlateforme,CPU,CarteMere,RAM,Stockage,DescPlateforme,InfoSupPlateforme,CodeCategorie) VALUES('Samsung','Samsung Galaxy S6','octocœur 2.1GHz de 64 bits','Exynos 7420','32 Go','3 Go','Téléphone intelligent Android de plus gros format','Nano SIM','Mobile');
INSERT INTO Jeux.tblPlateforme(CodePlateforme,NomPlateforme,CPU,CarteMere,RAM,Stockage,DescPlateforme,InfoSupPlateforme,CodeCategorie) VALUES('Apple','IPhone 5s','Double coeur 1.3 GHz Cyclone','Puce A7 à architecture 64 bits Coprocesseur de mouvement M7','1 Go DDR3','16-32 Go','Téléphone intelligent Apple d''une version antérieur','Nano-SIM','Mobile');
INSERT INTO Jeux.tblPlateforme(CodePlateforme,NomPlateforme,CPU,CarteMere,RAM,Stockage,DescPlateforme,InfoSupPlateforme,CodeCategorie) VALUES('Apple','IPhone 6','Double coeur 1.4 GHz Cyclone','Puce A8 à architecture 64 bits Coprocesseur de mouvement M8','1 Go DDR3','16-64 Go','Téléphone intelligent Apple petit format','Nano-SIM','Mobile');
INSERT INTO Jeux.tblPlateforme(CodePlateforme,NomPlateforme,CPU,CarteMere,RAM,Stockage,DescPlateforme,InfoSupPlateforme,CodeCategorie) VALUES('Apple','IPhone 6 Plus','Double coeur 1.4 GHz Cyclone','Puce A8 à architecture 64 bits Coprocesseur de mouvement M8','1 Go DDR3','16-64 Go','Téléphone intelligent Apple de format Moyen','Nano-SIM','Mobile');
INSERT INTO Jeux.tblPlateforme(CodePlateforme,NomPlateforme,CPU,CarteMere,RAM,Stockage,DescPlateforme,CodeCategorie) VALUES('Apple','Ipad Air','Double coeur 1.3 GHz Cyclone','Puce A7 à architecture 64 bits','1 Go DDR3','16-32 Go','Tablette Apple','Tablet');
INSERT INTO Jeux.tblPlateforme(CodePlateforme,NomPlateforme,CPU,CarteMere,RAM,Stockage,DescPlateforme,CodeCategorie) VALUES('WinSurf','Surface Windows','NVIDIA TEGRA 3 Quad Core CPU 1.30 GHz','Atmel','2Go','32 Go','Tablette qui contient Windows 8','Tablet');
INSERT INTO Jeux.tblPlateforme(CodePlateforme,NomPlateforme,CPU,CarteMere,RAM,Stockage,DescPlateforme,InfoSupPlateforme,CodeCategorie) VALUES('Android','Galaxy Tab A','quadruple coeur APQ 8016 de 1,2 GHz','Galaxy Tab motherboard','1.5Go','128 Go','Tablette Android de Grand format','Contient une plus grande memoire dû à sa carte mémoire','Tablet');
INSERT INTO Jeux.tblPlateforme(CodePlateforme,NomPlateforme,CPU,CarteMere,RAM,Stockage,DescPlateforme,CodeCategorie) VALUES('PS4','Playstation 4','low power x86-64 AMD “Jaguar”, 8 cores    ','PS4 motherboard','GDDR5 8Go','500 Go','Console salon de Sony la plus récente','ConSal');
INSERT INTO Jeux.tblPlateforme(CodePlateforme,NomPlateforme,CPU,CarteMere,RAM,Stockage,DescPlateforme,CodeCategorie) VALUES('PSVita','Playstation Vita','arm cortex A9 quad core up to 2ghz','PS Vita motherboard','512 Mo','4-32 Go','Console portative de Sonyqui peut se connecter sur le PlayStation Store ','ConPort');
INSERT INTO Jeux.tblPlateforme(CodePlateforme,NomPlateforme,CPU,CarteMere,RAM,Stockage,DescPlateforme,CodeCategorie) VALUES('XboxOne','Xbox One','8 Core AMD custom 1.75 GHz',' AMD "Jaguar" Accelerated Processing Unit','8Go DDR3','500 Go','Console salon de Microsoft la plus récente','ConSal');
INSERT INTO Jeux.tblPlateforme(CodePlateforme,NomPlateforme,CPU,CarteMere,RAM,Stockage,DescPlateforme,CodeCategorie) VALUES('PS','Playstation 3','Cell Broadband Engine','PS3 motherboard','256 Mo','120 Go','Console salon de Sony','ConSal');
INSERT INTO Jeux.tblPlateforme(CodePlateforme,NomPlateforme,CPU,CarteMere,RAM,Stockage,DescPlateforme,CodeCategorie) VALUES('Xbox360','Xbox 360','triple coeur 64-bit','Winchester','512 Mo de GDDR3','250 Go','Console salon de Microsoft','ConSal');
INSERT INTO Jeux.tblPlateforme(CodePlateforme,NomPlateforme,CPU,CarteMere,RAM,Stockage,DescPlateforme,CodeCategorie) VALUES('WiiU','WiiU','multicœur de type IBM Power','Wii U Mainboard PCB','2 Go de DDR3','8-32 Go','Console Nintendo la plus récente','ConSal');
INSERT INTO Jeux.tblPlateforme(CodePlateforme,NomPlateforme,CPU,CarteMere,RAM,Stockage,DescPlateforme,CodeCategorie) VALUES('Mac','iMac','Intel Core i5 de quatrième génération','Intel 20" EMC 2133','8 Go','3 To','Ordinateur Apple','PCBur');
INSERT INTO Jeux.tblPlateforme(CodePlateforme,NomPlateforme,CPU,CarteMere,RAM,Stockage,DescPlateforme,InfoSupPlateforme,CodeCategorie) VALUES('3DS','3DS',null,null,null,null,'Console Nintendo qui utilise le 3D',null,null);

USE master;