USE dbProjetE2Test
GO
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Darkest dungeon','Darkest Dungeon est un jeu dont l''intérêt repose sur le stress provoqué par l''inconnu. Le joueur devra y monter une équipe de héros et les mener dans des lieux toujours plus effrayants pour leur faire combattre des monstres, mais aussi leurs peurs',1,'RP',25,1,'Jeu d''exploration de dungeon');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('FTL','Faster than Light. Le joueur a pour objectif de conduire son vaisseau d''un point A à un point B de la galaxie, en faisant face aux situations critiques qui se présentent à lui (attaques de pirates, dangers environnements), sur un mode aléatoire.',1,null,null,null,'Jeu consistant à livré des info sensible');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Halo 4 solo',NULL,1,'M',6,1,'Halo 4 est un jeu de tir en vue subjective sur Xbox 360. Septième jeu de la franchise Halo');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Halo 4 Multi local',NULL,1,'M',6,2,'Halo 4 est un jeu de tir en vue subjective sur Xbox 360. Septième jeu de la franchise Halo');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Halo 4 Multi en ligne',NULL,1,'M',6,3,'Halo 4 est un jeu de tir en vue subjective sur Xbox 360. Septième jeu de la franchise Halo');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Mario Kart 8 solo','Mario Kart 8 est un jeu de course. Mario et ses amis s''y affrontent a bord de karts ou de motos sur 32 circuits comprenant aussi bien des passages sous l''eau ou dans les airs que des loopings. Douze joueurs peuvent s''affronter en ligne ou 4 en local.',1,'E',1,1,'Jeu de karting de Nintendo');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Mario Kart 8 multi local','Mario Kart 8 est un jeu de course. Mario et ses amis s''y affrontent a bord de karts ou de motos sur 32 circuits comprenant aussi bien des passages sous l''eau ou dans les airs que des loopings. Douze joueurs peuvent s''affronter en ligne ou 4 en local.',1,'E',1,2,'Jeu de karting de Nintendo');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Mario Kart 8 multi en ligne','Mario Kart 8 est un jeu de course. Mario et ses amis s''y affrontent a bord de karts ou de motos sur 32 circuits comprenant aussi bien des passages sous l''eau ou dans les airs que des loopings. Douze joueurs peuvent s''affronter en ligne ou 4 en local.',1,'E',1,3,'Jeu de karting de Nintendo');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('World of warcraft','World of Warcraft vous transporte dans le monde heroic-fantasy d''Azeroth où la guerre fait rage entre la Horde et l''Alliance. Affronter des hordes de monstres seul ou en groupe, constituer des guildes, et tellement plus encore.',1,'T',19,4,'Jeu de collection d''équpement');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('World of warcraft : Cataclysm','La 3ème extension de World of Warcraft, Cataclysm. le grand retour du tout puissant Deathwing qui va entraîner dans son sillage un changement radical de la topographie des continents. Arriver jusqu''au niveau 85 avec 2 nouvelles races',1,'T',19,4,'Jeu de collection d''équpement');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('NHL 15 solo','NHL 15 est une simulation de hockey sur glace. Ce nouvel épisode propose diverses améliorations physiques et graphiques, une foule d''aspect plus vivant, un nouveau commentateur ainsi que de nouvelles arènes exclusives.',1,'E10',40,1,'Jeu de hockey');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('NHL 15 Multi local','NHL 15 est une simulation de hockey sur glace. Ce nouvel épisode propose diverses améliorations physiques et graphiques, une foule d''aspect plus vivant, un nouveau commentateur ainsi que de nouvelles arènes exclusives.',1,'E10',40,2,'Jeu de hockey');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('NHL 15 multi en ligne','NHL 15 est une simulation de hockey sur glace. Ce nouvel épisode propose diverses améliorations physiques et graphiques, une foule d''aspect plus vivant, un nouveau commentateur ainsi que de nouvelles arènes exclusives.',1,'E10',40,3,'Jeu de hockey');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('NHL 14 solo','NHL 14 est un jeu de hockey sur glace. Le joueur peut s''y prendre pour un professionnel et gérer sa propre carrière ou bien gérer l''avenir d''une franchise dans le mode DG. Des matchs old-school inspirés par NHL 94 sont également au programme.',1,'E10',40,1,'Jeu de hockey');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('NHL 14 Multi local','NHL 14 est un jeu de hockey sur glace. Le joueur peut s''y prendre pour un professionnel et gérer sa propre carrière ou bien gérer l''avenir d''une franchise dans le mode DG. Des matchs old-school inspirés par NHL 94 sont également au programme.',1,'E10',40,2,'Jeu de hockey');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('NHL 14 multi en ligne','NHL 14 est un jeu de hockey sur glace. Le joueur peut s''y prendre pour un professionnel et gérer sa propre carrière ou bien gérer l''avenir d''une franchise dans le mode DG. Des matchs old-school inspirés par NHL 94 sont également au programme.',1,'E10',40,3,'Jeu de hockey');


INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Fallout 3','Fallout 3 est un jeu de rôle en 3D se déroulant dans un monde post-apocalyptique. Le joueur y fait évoluer son personnage comme il le souhaite et choisit la façon dont il va communiquer et interagir avec les autres personnages. ',1,'M',43,1,'Jeu de Survie Post-Apocalyptique');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Borderlands Solo','Borderlands est un jeu de tir à la première personne mâtiné de jeu de rôle (expérience, spécialisations) qui vous entraîne sur une planète mystérieuse, aux allures de Far West futuriste',1,'M',43,1,'Jeu d''aventure dans un univers Steampunk');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Bordelands Multi Local','Borderlands est un jeu de tir à la première personne mâtiné de jeu de rôle (expérience, spécialisations) qui vous entraîne sur une planète mystérieuse, aux allures de Far West futuriste',1,'M',43,2,'Jeu d''aventure dans un univers Steampunk');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Bordelands Multi En Ligne','Borderlands est un jeu de tir à la première personne mâtiné de jeu de rôle (expérience, spécialisations) qui vous entraîne sur une planète mystérieuse, aux allures de Far West futuriste',1,'M',43,3,'Jeu d''aventure dans un univers Steampunk');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Soul Calibur 5 Solo',' Jeu de combat, SoulCalibur V est le septième épisode de la célèbre franchise "Soul" placé sous le signe du renouveau. Prenant place 17 ans après les événements de SoulCalibur IV, c''est au tour de Patroklos, le fils de Sophitia, de rejoindre la quête de la Soul Edge',1,'T',2,1,'Jeu de combat ');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Soul Calibur 5 Multi En Local',' Jeu de combat, SoulCalibur V est le septième épisode de la célèbre franchise "Soul" placé sous le signe du renouveau. Prenant place 17 ans après les événements de SoulCalibur IV, c''est au tour de Patroklos, le fils de Sophitia, de rejoindre la quête de la Soul Edge',1,'T',2,2,'Jeu de combat ');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Soul Calibur 5 Multi En Ligne',' Jeu de combat, SoulCalibur V est le septième épisode de la célèbre franchise "Soul" placé sous le signe du renouveau. Prenant place 17 ans après les événements de SoulCalibur IV, c''est au tour de Patroklos, le fils de Sophitia, de rejoindre la quête de la Soul Edge',1,'T',2,3,'Jeu de combat ');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Naruto Shippuden : Ult Ninja Storm 3 Solo','Jeu d''aventure et de combat, Naruto Shippuden : Ultimate Ninja Storm 3 reprend les bases du gameplay de la série en y ajoutant quelques nouveautés, comme les actions cachées, les combats de horde ou encore les décisions ultimes qui offrent diverses possibilités',1,'T',2,1,'Jeu de combat ');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Naruto Shippuden : Ult Ninja Storm 3 Multi Local','Jeu d''aventure et de combat, Naruto Shippuden : Ultimate Ninja Storm 3 reprend les bases du gameplay de la série en y ajoutant quelques nouveautés, comme les actions cachées ou les combats de horde',1,'T',2,2,'Jeu de combat ');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Naruto Shippuden : Ult Ninja Storm 3 Multi Ligne','Jeu d''aventure et de combat, Naruto Shippuden : Ultimate Ninja Storm 3 reprend les bases du gameplay de la série en y ajoutant quelques nouveautés, comme les actions cachées ou les combats de horde',1,'T',2,3,'Jeu de combat ');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('The Elder Scrolls V : Skyrim','L''histoire se déroule dans la contrée de Skyrim, près de 200 ans après les événements narrés dans le précédent opus. L''assassinat du Haut-Roi de Bordeciel a plongé le pays dans la guerre civile et pour couronner le tout, c''est le moment que choisit Alduin pour réapparaître.',1,'M',19,1,'Jeu de découverte dans un univers médiéval');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('The Elder Scrolls IV : Oblivion','Jeu de rôle se passant dans un grand monde ouvert, The Elder Scrolls IV : Oblivion permet au joueur d''incarner un héros guerrier. Il peut explorer la carte gigantesque pour découvrir des donjons, vaincre des boss, découvrir des trésors fabuleux, et accomplir des quêtes.',1,'M',19,1,'Jeu de découverte dans un univers médiéval');


INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Destiny','Destiny est un MMO FPS dans lequel le joueur se bat dans un contexte futuriste. Celui-ci doit lutter contre des hordes d''aliens. Celui-ci peut améliorer ses armes en récoltant des matériaux dans les zones du jeu, puis participer à des combats où la stratégie prime.',1,'T',6,4,'Jeu  d''extermination d''alien');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Destiny : Le roi des corrompus','3e Extension de Destiny avec une nouvelle planète, de nouveau ennemis, de nouvelle capacité, d''ajout au PVP et bien plus',1,'T',6,4,'Jeu  d''extermination d''alien');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Assassins Creed Syndicate solo','Prenant place dans le Londres de l''époque victorienne, Assassin''s Creed Syndicate est un jeu d''action-aventure en monde ouvert. Parmi les nouveautés, on peut notamment citer la possibilité de se déplacer sur des éléments en mouvement (calèche par exemple).',1,'M',15,1,'Jeu d''assassinat');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Assassins Creed Syndicate Multi en ligne','Prenant place dans le Londres de l''époque victorienne, Assassin''s Creed Syndicate est un jeu d''action-aventure en monde ouvert. Parmi les nouveautés, on peut notamment citer la possibilité de se déplacer sur des éléments en mouvement (calèche par exemple).',1,'M',15,3,'Jeu d''assassinat');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('World of tank','Jeu de stratégie et de combat, World of Tanks vous place dans un tank. Aux commandes de votre char, vous affrontez des joueurs dans des parties en 15 contre 15 quelque peu mouvementées. Plus de 60 véhicules sont disponibles. Vous pouvez améliorer votre tank grâce à des crédits remportés au fur et à mesure des parties, et également via la boutique.',1,'T',5,3,'Jeu de combat de tank');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Counter-Strike : Global Offensive solo','Les joueurs y choisissent le camp des terroristes ou des anti-terroristes avant de s''affronter dans des batailles sans merci. Plusieurs modes de jeux sont disponibles (dont un d''entraînement) et les combattants ont accès à plus de trente armes différentes.',1,'M',6,1,'Jeu  de tir compétitif');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Counter-Strike : Global Offensive Multi en ligne','Les joueurs y choisissent le camp des terroristes ou des anti-terroristes avant de s''affronter dans des batailles sans merci. Plusieurs modes de jeux sont disponibles (dont un d''entraînement) et les combattants ont accès à plus de trente armes différentes.',1,'M',6,3,'Jeu  de tir compétitif');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('TowerFall Asc Solo','Jeu de combat d''archerie sur plates-formes. Les joueurs se mesurent les uns aux autres en récupérant des objets magiques dans des coffres et en essayant d''esquiver les tirs de leurs adversaires.',1,'E10',2,1,'Jeu de combat à l''arc');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('TowerFall Asc Multi local','Jeu de combat d''archerie sur plates-formes. Les joueurs se mesurent les uns aux autres en récupérant des objets magiques dans des coffres.',1,'E10',2,2,'Jeu de combat à l''arc');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Skyforge','Skyforge est un MMORPG sur PC. Dans un monde de haute technologie où la fantasy se mêle à la science-fiction et les mystères antiques, Skyforge transporte les joueurs dans un univers hors du commun où les mortels et les immortels se battent pour survivre contre les dieux envahisseurs et leurs armées.',1,'RP',19,4,'Jeu de dieu');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Team Fortress 2 Solo','Team Fortress 2 est un FPS en ligne se déroulant dans un univers cartoon et caricatural. Le joueur peut choisir entre plusieurs personnages ayant chacun des capacités différentes, trouver de nombreuses armes et affronter ses pairs en multijoueur dans de nombreuses arènes et sur 6 cartes.',1,'M',6,1,'Jeu de tir compétitif');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Team Fortress 2 Multi en ligne','Team Fortress 2 est un FPS en ligne se déroulant dans un univers cartoon et caricatural. Le joueur peut choisir entre plusieurs personnages ayant chacun des capacités différentes, trouver de nombreuses armes et affronter ses pairs en multijoueur dans de nombreuses arènes et sur 6 cartes.',1,'M',6,3,'Jeu de tir compétitif');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Dream Pinball 3D ','Dream Pinball 3D est un jeu de flipper qui propose plus de 7 tables différentes, aux thèmes variés et aux nombreux combos et multiplicateurs de points. Trouvez les rampes, les souterrains et les bonus pour devenir docteur flipper.',1,'E10',42,1,'Jeu de Pinball');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Super Mario Maker','Mario Maker est un jeu de plates-formes et d''édition de niveaux pour WiiU. Le joueur peut y choisir entre une esthétique moderne ou ancienne façon NES, et créer simplement ses environnements, placer des ennemis etc.',1,'E',43,1,'Jeu de plateforme');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Forza Motorsport 5 solo','Forza Motorsport 5 est un jeu de course orienté simulation sur Xbox One. Le joueur peut y parcourir 14 circuits allant de Yas Marina à Spa Francorchamps au volant de 200 voitures différentes. L''IA s''adapte sur le comportement de vrais joueurs tandis qu''un mode multijoueur en ligne ou en écran splitté complète le tableau.',1,'E',1,1,'Jeu de course automobile');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Forza Motorsport 5 multi local','Forza Motorsport 5 est un jeu de course orienté simulation sur Xbox One. Le joueur peut y parcourir 14 circuits allant de Yas Marina à Spa Francorchamps au volant de 200 voitures différentes. L''IA s''adapte sur le comportement de vrais joueurs tandis qu''un mode multijoueur en ligne ou en écran splitté complète le tableau.',1,'E',1,2,'Jeu de course automobile');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Forza Motorsport 5 multi en ligne','Forza Motorsport 5 est un jeu de course orienté simulation sur Xbox One. Le joueur peut y parcourir 14 circuits allant de Yas Marina à Spa Francorchamps au volant de 200 voitures différentes. L''IA s''adapte sur le comportement de vrais joueurs tandis qu''un mode multijoueur en ligne ou en écran splitté complète le tableau.',1,'E',1,3,'Jeu de course automobile');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('The Witcher 3 : Wild Hunt','The Witcher 3 : Wild Hunt est un Action-RPG se déroulant dans un monde ouvert. Troisième épisode de la série du même nom, inspirée des livres du polonais Andrzej Sapkowski, cet opus relate la fin de l''histoire de Geralt de Riv.',1,'M',21,1,'Jeu de chasse au monstre magique');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('The Witcher 2 : Assassins of Kings','Action-RPG inspiré des livres d''Andrzej Sapkowski, The Witcher 2 : Assassins of Kings se déroule dans un monde médiéval et fantastique. Le joueur y incarne Geralt, un chasseur de monstres mêlé à une intrigue politique dans le royaume de Téméria. Il devra mettre un terme à la rébellion de l''Ordre de la Rose Ardente.',1,'M',21,1,'Jeu de chasse au monstre magique');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Call of Duty : Black Ops III solo',' Il s''agit du 12e épisode principal de la série Call of Duty. C''est également le 3e opus de la saga Black Ops et le 6e épisode de la série développé par le studio Treyarch. Le jeu amène une nouvelle campagne, un renouvellement du multijoueur et une reforme du fameux mode zombie.',1,'RP',6,1,'Jeu de tir');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Call of Duty : Black Ops III multi Local',' Il s''agit du 12e épisode principal de la série Call of Duty. C''est également le 3e opus de la saga Black Ops et le 6e épisode de la série développé par le studio Treyarch. Le jeu amène une nouvelle campagne, un renouvellement du multijoueur et une reforme du fameux mode zombie.',1,'RP',6,2,'Jeu de tir');
INSERT INTO Jeux.tblJeu(NomJeu,InfoSupJeu,Actif,CoteESRB,IdGenre,IdMode,DescJeu)VALUES('Call of Duty : Black Ops III Multi en ligne',' Il s''agit du 12e épisode principal de la série Call of Duty. C''est également le 3e opus de la saga Black Ops et le 6e épisode de la série développé par le studio Treyarch. Le jeu amène une nouvelle campagne, un renouvellement du multijoueur et une reforme du fameux mode zombie.',1,'RP',6,3,'Jeu de tir');
GO
USE master;